/* tables */
CREATE TABLE Cryteria (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(256) UNIQUE NOT NULL
);

CREATE TABLE Universities (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(256) UNIQUE NOT NULL
);

CREATE TABLE CryteriaValues (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	universityID INTEGER NOT NULL,
	cryteriaID INTEGER NOT NULL,
	cryteriaValue VARCHAR(256) NOT NULL,
	FOREIGN KEY(universityID) REFERENCES Universities(id) ON DELETE CASCADE,
	FOREIGN KEY(cryteriaID) REFERENCES Cryteria(id) ON DELETE CASCADE
);

/* initial values */
INSERT INTO Cryteria(name) VALUES('Preferencje pracodawców');
INSERT INTO Cryteria(name) VALUES('Uznania międzynarodowe');
INSERT INTO Cryteria(name) VALUES('Zaplecze innowacyjne uczelni');
INSERT INTO Cryteria(name) VALUES('Nasycenie kadry osobami o najwyższych kwalifikacjach');
INSERT INTO Cryteria(name) VALUES('Dostępność dla studentów kadr wysokokwalifikowanych');
INSERT INTO Cryteria(name) VALUES('Elektroniczne zasoby biblioteczne');
INSERT INTO Cryteria(name) VALUES('Drukowane zasoby biblioteczne');
INSERT INTO Cryteria(name) VALUES('Wymiana studencka (wyjazdy)');
INSERT INTO Cryteria(name) VALUES('Odległość uczelni od miejsca zamieszkania');
INSERT INTO Cryteria(name) VALUES('Bezpłatne studia');

INSERT INTO Universities(name) VALUES('Uniwersytet Jagielloński');
INSERT INTO Universities(name) VALUES('Uniwersytet Warszawski');
INSERT INTO Universities(name) VALUES('Uniwersytet imienia Adama Mickiewicza w Poznaniu');
INSERT INTO Universities(name) VALUES('Politechnika Warszawska');
INSERT INTO Universities(name) VALUES('Politechnika Wrocławska');
INSERT INTO Universities(name) VALUES('Akademia Górniczo-Hutnicza imienia Stanisława Staszica w Krakowie');
INSERT INTO Universities(name) VALUES('Uniwersytet Wrocławski');
INSERT INTO Universities(name) VALUES('Politechnika Łódzka');
INSERT INTO Universities(name) VALUES('Uniwersytet Mikołaja Kopernika w Toruniu');
INSERT INTO Universities(name) VALUES('Uniwersytet Medyczny imienia Karola Marcinkowskiego w Poznaniu');
INSERT INTO Universities(name) VALUES('Akademia Leona Koźmińskiego w Warszawie');
INSERT INTO Universities(name) VALUES('Szkoła Główna Handlowa w Warszawie');
INSERT INTO Universities(name) VALUES('Uniwersytet Medyczny w Łodzi');
INSERT INTO Universities(name) VALUES('Warszawski Uniwersytet Medyczny');
INSERT INTO Universities(name) VALUES('Uniwersytet Gdański');
INSERT INTO Universities(name) VALUES('Politechnika Śląska w Gliwicach');
INSERT INTO Universities(name) VALUES('Uniwersytet Medyczny w Białymstoku');
INSERT INTO Universities(name) VALUES('Gdański Uniwersytet Medyczny');
INSERT INTO Universities(name) VALUES('Uniwersytet Śląski w Katowicach');
INSERT INTO Universities(name) VALUES('Politechnika Gdańska');
INSERT INTO Universities(name) VALUES('Politechnika Poznańska');
INSERT INTO Universities(name) VALUES('Akademia Medyczna imienia Piastów Śląskich we Wrocławiu');
INSERT INTO Universities(name) VALUES('Uniwersytet Ekonomiczny w Poznaniu');
INSERT INTO Universities(name) VALUES('Uniwersytet Łódzki');
INSERT INTO Universities(name) VALUES('Szkoła Główna Gospodarstwa Wiejskiego w Warszawie');
INSERT INTO Universities(name) VALUES('Uniwersytet Warmińsko-Mazurski w Olsztynie');
INSERT INTO Universities(name) VALUES('Śląski Uniwersytet Medyczny w Katowicach');
INSERT INTO Universities(name) VALUES('Katolicki Uniwersytet Lubelski Jana Pawła II');
INSERT INTO Universities(name) VALUES('Uniwersytet Przyrodniczy we Wrocławiu');
INSERT INTO Universities(name) VALUES('Uniwersytet Medyczny w Lublinie');
INSERT INTO Universities(name) VALUES('Uniwersytet Marii Curie-Skłodowskiej w Lublinie');
INSERT INTO Universities(name) VALUES('Pomorski Uniwersytet Medyczny w Szczecinie');
INSERT INTO Universities(name) VALUES('Uniwersytet Rolniczy imienia Hugona Kołłątaja w Krakowie');
INSERT INTO Universities(name) VALUES('Uniwersytet Przyrodniczy w Poznaniu');
INSERT INTO Universities(name) VALUES('Uniwersytet Ekonomiczny we Wrocławiu');
INSERT INTO Universities(name) VALUES('Uniwersytet Ekonomiczny w Krakowie');
INSERT INTO Universities(name) VALUES('Wojskowa Akademia Techniczna imienia Jarosława Dąbrowskiego w Warszawie');
INSERT INTO Universities(name) VALUES('Uniwersytet Papieski Jana Pawła II w Krakowie');
INSERT INTO Universities(name) VALUES('Zachodniopomorski Uniwersytet Technologiczny w Szczecinie');
INSERT INTO Universities(name) VALUES('Politechnika Krakowska imienia Tadeusza Kościuszki');
INSERT INTO Universities(name) VALUES('Uniwersytet Kardynała Stefana Wyszyńskiego w Warszawie');
INSERT INTO Universities(name) VALUES('Uniwersytet Ekonomiczny w Katowicach');
INSERT INTO Universities(name) VALUES('Polsko-Japońska Wyższa Szkoła Technik Komputerowych w Warszawie');
INSERT INTO Universities(name) VALUES('Uniwersytet Opolski');
INSERT INTO Universities(name) VALUES('Politechnika Częstochowska');
INSERT INTO Universities(name) VALUES('Uniwersytet Pedagogiczny imienia Komisji Edukacji Narodowej w Krakowie');
INSERT INTO Universities(name) VALUES('Uniwersytet w Białymstoku');
INSERT INTO Universities(name) VALUES('Uniwersytet Szczeciński');
INSERT INTO Universities(name) VALUES('Politechnika Opolska');
INSERT INTO Universities(name) VALUES('Politechnika Białostocka');
INSERT INTO Universities(name) VALUES('Politechnika Rzeszowska imienia Ignacego Łukasiewicza');
INSERT INTO Universities(name) VALUES('Politechnika Lubelska');
INSERT INTO Universities(name) VALUES('Politechnika Świętokrzyska w Kielcach');
INSERT INTO Universities(name) VALUES('Uniwersytet Rzeszowski');
INSERT INTO Universities(name) VALUES('Szkoła Wyższa Psychologii Społecznej w Warszawie');
INSERT INTO Universities(name) VALUES('Akademia Obrony Narodowej w Warszawie');
INSERT INTO Universities(name) VALUES('Uniwersytet Humanistyczno-Przyrodniczy Jana Kochanowskiego w Kielcach');
INSERT INTO Universities(name) VALUES('Uniwersytet Zielonogórski');
INSERT INTO Universities(name) VALUES('Uniwersytet Technologiczno-Przyrodniczy imienia J. i J. Śniadeckich w Bydgoszczy');
INSERT INTO Universities(name) VALUES('Collegium Civitas w Warszawie');
INSERT INTO Universities(name) VALUES('Uniwersytet Kazimierza Wielkiego w Bydgoszczy');
INSERT INTO Universities(name) VALUES('Akademia Wychowania Fizycznego we Wrocławiu');
INSERT INTO Universities(name) VALUES('Społeczna Akademia Nauk w Łodzi');
INSERT INTO Universities(name) VALUES('Politechnika Koszalińska');
INSERT INTO Universities(name) VALUES('Akademia Humanistyczna imienia Aleksandra Gieysztora w Pułtusku');
INSERT INTO Universities(name) VALUES('Akademia Wychowania Fizycznego imienia Bronisława Czecha w Krakowie');
INSERT INTO Universities(name) VALUES('Akademia Pedagogiki Specjalnej imienia Marii Grzegorzewskiej w Warszawie');
INSERT INTO Universities(name) VALUES('Akademia Techniczno-Humanistyczna w Bielsku-Białej');
INSERT INTO Universities(name) VALUES('Akademia Wychowania Fizycznego Józefa Piłsudskiego w Warszawie');
INSERT INTO Universities(name) VALUES('Akademia Wychowania Fizycznego imienia Eugeniusza Piaseckiego w Poznaniu');
INSERT INTO Universities(name) VALUES('Politechnika Radomska imienia Kazimierza Pułaskiego');
INSERT INTO Universities(name) VALUES('Uniwersytet Przyrodniczo-Humanistyczny w Siedlcach');
INSERT INTO Universities(name) VALUES('Uczelnia Łazarskiego w Warszawie');
INSERT INTO Universities(name) VALUES('Akademia Finansów w Warszawie');
INSERT INTO Universities(name) VALUES('Akademia imienia Jana Długosza w Częstochowie');
INSERT INTO Universities(name) VALUES('Dolnośląska Szkoła Wyższa we Wrocławiu');
INSERT INTO Universities(name) VALUES('Wyższa Szkoła Finansów i Zarządzania w Warszawie');
INSERT INTO Universities(name) VALUES('Akademia Pomorska w Słupsku');
INSERT INTO Universities(name) VALUES('Górnośląska Wyższa Szkoła Handlowa imienia W. Korfantego w Katowicach');
INSERT INTO Universities(name) VALUES('Krakowska Akademia imienia Andrzeja Frycza Modrzewskiego');
INSERT INTO Universities(name) VALUES('Akademia Morska w Gdyni');
INSERT INTO Universities(name) VALUES('Wyższa Szkoła Filozoficzno-Pedagogiczna „Ignatianum” w Krakowie');
INSERT INTO Universities(name) VALUES('Akademia Morska w Szczecinie');
INSERT INTO Universities(name) VALUES('Akademia Humanistyczno-Ekonomiczna w Łodzi');
INSERT INTO Universities(name) VALUES('Akademia Marynarki Wojennej imienia Bohaterów Westerplatte w Gdyni');
INSERT INTO Universities(name) VALUES('Akademia Wychowania Fizycznego i Sportu imienia Jędrzeja Śniadeckiego w Gdańsku');
INSERT INTO Universities(name) VALUES('Wyższa Szkoła Studiów Międzynarodowych w Łodzi');
INSERT INTO Universities(name) VALUES('Wyższa Szkoła Zarządzania Marketingowego i Języków Obcych w Katowicach');

INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '1', '90,53');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '2', '96,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '4', '56,35');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '5', '46,83');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '6', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '7', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '8', '59,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '1', '98,88');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '2', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '4', '62,66');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '5', '43,73');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '6', '33,88');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '7', '87,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '8', '71,52');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '1', '77,17');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '2', '15,74');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '4', '55,11');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '5', '39,70');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '6', '72,92');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '7', '69,64');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '8', '61,59');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '1', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '2', '32,15');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '4', '45,25');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '5', '36,85');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '6', '60,36');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '7', '24,52');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '8', '32,10');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '1', '97,70');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '2', '8,64');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '4', '44,34');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '5', '32,59');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '6', '47,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '7', '18,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '8', '31,39');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '1', '98,49');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '2', '11,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '4', '45,39');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '5', '33,81');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '6', '37,06');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '7', '20,01');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '8', '18,57');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '1', '69,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '2', '8,46');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '4', '55,11');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '5', '38,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '6', '48,83');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '7', '49,56');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '8', '53,09');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '1', '74,87');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '2', '0,87');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '4', '40,33');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '5', '40,56');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '6', '33,32');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '7', '13,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '8', '53,01');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '1', '64,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '2', '4,97');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '4', '56,58');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '5', '36,44');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '6', '35,73');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '7', '72,63');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '8', '33,07');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '1', '39,61');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '2', '2,15');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '4', '45,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '5', '84,05');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '6', '35,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '7', '14,97');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '8', '15,20');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '1', '63,62');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '2', '49,60');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '4', '62,07');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '5', '24,02');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '6', '54,10');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '7', '14,20');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '8', '90,05');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '1', '93,82');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '2', '33,94');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '4', '52,65');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '5', '43,56');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '6', '33,83');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '7', '19,09');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '8', '99,48');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '1', '55,59');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '2', '1,04');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '4', '44,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '5', '98,16');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '6', '36,62');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '7', '10,82');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '8', '14,53');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '1', '63,49');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '2', '2,11');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '4', '34,81');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '5', '75,74');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '6', '30,20');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '7', '11,79');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '8', '52,07');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '1', '61,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '2', '1,20');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '4', '50,80');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '5', '32,49');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '6', '57,25');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '7', '50,14');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '8', '32,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '1', '91,25');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '2', '5,67');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '4', '38,53');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '5', '38,49');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '6', '16,98');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '7', '23,25');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '8', '23,51');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '1', '48,29');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '2', '1,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '4', '52,96');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '5', '79,77');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '6', '56,01');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '7', '12,37');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '8', '12,35');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '1', '43,62');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '2', '1,53');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '4', '35,24');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '5', '81,26');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '6', '51,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '7', '14,27');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '8', '25,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '1', '50,66');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '2', '5,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '4', '55,44');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '5', '39,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '6', '29,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '7', '36,52');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '8', '33,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '1', '65,33');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '2', '1,29');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '4', '45,19');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '5', '23,83');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '6', '27,79');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '7', '13,69');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '8', '26,86');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '1', '86,71');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '2', '0,96');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '4', '39,96');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '5', '31,78');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '6', '22,65');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '7', '22,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '8', '34,37');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '1', '70,26');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '2', '0,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '4', '40,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '5', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '6', '46,05');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '7', '14,43');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '8', '36,60');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '1', '91,84');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '4', '55,68');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '5', '26,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '6', '66,17');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '7', '22,03');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '8', '62,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '1', '56,05');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '2', '15,48');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '4', '47,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '5', '30,56');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '6', '31,14');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '7', '68,10');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '8', '31,93');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '1', '73,16');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '2', '2,93');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '4', '50,02');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '5', '34,39');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '6', '74,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '7', '17,71');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '8', '28,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '1', '68,55');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '2', '3,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '4', '50,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '5', '35,17');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '6', '46,39');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '7', '25,51');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '8', '12,50');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '1', '29,61');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '2', '1,58');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '4', '44,31');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '5', '75,48');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '6', '20,36');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '7', '23,51');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '8', '14,05');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '1', '67,70');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '2', '1,15');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '4', '50,71');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '5', '42,73');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '6', '17,37');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '7', '47,25');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '8', '28,49');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '1', '33,68');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '4', '60,06');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '5', '39,98');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '6', '65,87');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '7', '15,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '8', '26,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '1', '21,64');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '2', '1,47');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '4', '34,93');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '5', '80,87');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '6', '40,09');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '7', '10,32');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '8', '13,56');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '1', '68,62');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '2', '1,98');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '4', '46,06');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '5', '38,02');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '6', '35,33');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '7', '52,37');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '8', '22,22');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '1', '3,55');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '2', '1,37');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '4', '49,12');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '5', '76,12');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '6', '49,65');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '7', '22,92');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '8', '12,80');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '1', '59,08');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '2', '0,68');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '4', '59,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '5', '41,49');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '6', '23,71');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '7', '16,56');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '8', '17,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '1', '57,70');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '2', '0,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '4', '58,83');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '5', '48,69');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '6', '12,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '7', '12,27');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '8', '16,35');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '1', '72,76');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '4', '36,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '5', '25,83');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '6', '28,32');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '7', '18,84');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '8', '32,78');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '1', '74,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '2', '0,73');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '4', '32,92');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '5', '17,02');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '6', '41,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '7', '14,44');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '8', '43,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '1', '51,97');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '2', '2,16');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '4', '43,27');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '5', '39,26');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '6', '52,65');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '7', '16,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '8', '12,21');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '1', '3,22');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '4', '80,80');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '5', '51,82');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '6', '8,66');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '7', '13,12');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '8', '9,79');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '1', '15,13');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '2', '2,50');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '4', '48,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '5', '49,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '6', '31,26');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '7', '13,83');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '8', '22,61');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '1', '53,88');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '2', '4,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '4', '36,80');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '5', '34,76');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '6', '30,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '7', '13,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '8', '28,94');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '1', '41,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '2', '1,57');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '4', '71,14');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '5', '26,54');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '6', '49,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '7', '41,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '8', '12,20');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '1', '65,26');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '4', '42,47');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '5', '16,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '6', '12,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '7', '13,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '8', '31,31');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '1', '41,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '2', '1,55');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '4', '65,45');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '5', '31,47');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '6', '4,68');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '7', '44,63');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '8', '13,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '1', '34,01');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '2', '1,03');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '4', '60,60');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '5', '28,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '6', '16,09');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '7', '54,33');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '8', '16,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '1', '35,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '2', '2,44');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '4', '39,85');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '5', '38,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '6', '11,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '7', '9,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '8', '4,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '1', '33,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '2', '0,86');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '4', '49,39');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '5', '29,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '6', '30,25');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '7', '17,33');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '8', '35,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '1', '31,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '2', '2,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '4', '44,97');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '5', '28,90');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '6', '16,74');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '7', '26,80');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '8', '22,86');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '1', '41,84');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '4', '48,07');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '5', '28,09');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '6', '24,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '7', '22,25');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '8', '18,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '1', '22,37');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '4', '48,63');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '5', '26,94');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '6', '20,61');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '7', '15,86');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '8', '31,09');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '1', '42,37');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '2', '3,09');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '4', '37,24');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '5', '26,10');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '6', '28,62');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '7', '59,05');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '8', '30,70');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '1', '38,03');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '2', '2,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '4', '38,66');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '5', '21,14');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '6', '10,67');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '7', '16,62');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '8', '11,29');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '1', '14,47');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '2', '2,27');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '4', '35,73');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '5', '26,35');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '6', '17,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '7', '18,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '8', '37,05');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '1', '30,66');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '4', '46,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '5', '19,86');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '6', '10,78');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '7', '20,47');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '8', '8,02');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '1', '33,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '2', '1,33');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '4', '43,25');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '5', '30,87');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '6', '10,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '7', '24,44');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '8', '17,82');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '1', '39,01');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '2', '0,96');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '4', '73,84');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '5', '18,12');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '6', '12,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '7', '33,30');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '8', '21,74');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '1', '6,58');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '4', '47,35');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '5', '15,42');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '6', '34,43');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '7', '10,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '8', '12,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '1', '33,55');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '2', '1,09');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '4', '46,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '5', '30,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '6', '11,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '7', '28,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '8', '13,15');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '1', '22,04');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '2', '0,84');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '4', '50,96');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '5', '34,08');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '6', '41,57');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '7', '18,73');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '8', '8,44');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '1', '14,93');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '2', '1,92');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '4', '44,65');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '5', '37,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '6', '14,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '7', '12,60');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '8', '13,70');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '1', '3,29');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '4', '97,19');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '5', '24,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '6', '2,17');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '7', '4,47');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '8', '59,44');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '1', '37,96');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '2', '1,26');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '4', '50,60');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '5', '26,15');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '6', '18,24');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '7', '15,10');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '8', '9,84');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '1', '3,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '4', '34,24');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '5', '34,79');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '6', '9,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '7', '8,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '8', '40,74');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '1', '17,96');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '2', '0,87');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '4', '66,87');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '5', '22,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '6', '30,32');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '7', '23,22');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '8', '14,45');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '1', '24,74');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '4', '50,67');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '5', '26,54');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '6', '24,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '7', '10,70');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '8', '7,57');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '1', '6,71');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '4', '65,50');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '5', '37,60');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '6', '33,05');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '7', '19,30');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '8', '1,51');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '1', '6,12');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '4', '30,37');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '5', '37,53');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '6', '10,38');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '7', '6,01');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '8', '30,74');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '1', '20,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '4', '41,29');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '5', '20,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '6', '8,22');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '7', '11,26');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '8', '9,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '1', '20,39');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '4', '43,80');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '5', '25,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '6', '14,63');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '7', '23,32');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '8', '33,67');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '1', '15,46');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '4', '37,25');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '5', '25,58');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '6', '8,43');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '7', '9,13');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '8', '46,64');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '1', '9,08');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '4', '38,06');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '5', '33,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '6', '13,92');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '7', '9,69');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '8', '81,32');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '1', '24,93');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '4', '49,88');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '5', '33,08');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '6', '32,17');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '7', '19,12');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '8', '7,56');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '1', '25,33');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '4', '51,86');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '5', '34,23');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '6', '24,24');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '7', '17,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '8', '9,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '1', '17,17');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '2', '0,77');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '4', '61,46');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '5', '16,65');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '6', '16,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '7', '7,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '8', '75,78');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '1', '27,57');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '4', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '5', '35,71');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '6', '5,69');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '7', '8,75');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '8', '20,97');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '1', '29,87');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '4', '50,03');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '5', '33,86');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '6', '17,94');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '7', '11,19');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '8', '5,18');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '1', '18,49');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '4', '52,16');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '5', '15,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '6', '3,48');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '7', '27,50');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '8', '14,88');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '1', '11,32');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '2', '1,08');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '4', '91,98');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '5', '13,97');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '6', '10,07');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '7', '41,55');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '8', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '1', '25,46');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '2', '1,02');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '4', '39,12');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '5', '45,05');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '6', '27,06');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '7', '13,58');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '8', '12,52');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '1', '8,82');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '3', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '4', '73,11');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '5', '14,02');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '6', '53,27');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '7', '41,67');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '8', '23,83');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '1', '24,34');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '4', '84,55');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '5', '22,51');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '6', '12,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '7', '30,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '8', '10,21');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '1', '16,84');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '2', '0,95');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '4', '35,86');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '5', '25,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '6', '9,89');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '7', '17,28');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '8', '17,23');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '1', '17,43');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '3', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '4', '53,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '5', '39,08');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '6', '4,88');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '7', '15,59');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '8', '7,23');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '1', '20,79');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '4', '37,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '5', '25,67');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '6', '22,43');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '7', '7,99');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '8', '7,81');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '1', '27,17');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '4', '67,79');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '5', '22,52');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '6', '11,61');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '7', '7,58');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '8', '2,81');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '1', '9,47');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '4', '46,70');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '5', '23,98');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '6', '0,82');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '7', '9,72');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '8', '3,81');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '1', '4,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '3', '25,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '4', '33,87');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '5', '24,66');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '6', '11,08');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '7', '6,79');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '8', '11,41');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '1', '4,54');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '3', '75,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '4', '64,66');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '5', '39,30');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '6', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '7', '18,91');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '8', '100,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '1', '2,30');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '2', '0,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '3', '50,00');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '4', '71,59');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '5', '23,27');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '6', '0,56');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '7', '8,70');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '8', '18,62');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '9', '50,061112;19,933183');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '9', '52,240402;21,019206');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '9', '52,408189;16,915663');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '9', '52,220501;21,0106927');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '9', '51,1073275;17,0618517');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '9', '50,065459;19,9197815');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '9', '51,113943;17,034504');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '9', '51,7529213;19,4499835');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '9', '53,0194329;18,5692211');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '9', '52,40962;16,918966');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '9', '52,2714446;21,0151543');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '9', '52,2089474;21,0092766');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '9', '51,7698503;19,454095');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '9', '53,0774065;21,5791509');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '9', '54,399716;18,568879');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '9', '50,2910822;18,6754411');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '9', '53,1305815;23,1653094');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '9', '54,3664071;18,629473');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '9', '50,2607617;19,0283579');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '9', '54,3711311;18,6177751');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '9', '52,3941701;16,918062');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '9', '51,1078852;17,0385376');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '9', '52,4062818;16,9184338');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '9', '51,7720115;19,4739492');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '9', '52,1619551;21,0430455');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '9', '53,7604844;20,4609888');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '9', '50,2250632;18,9539479');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '9', '51,2476569;22,5433342');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '9', '51,111423;17,064267');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '9', '51,2481569;22,5489466');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '9', '51,2456308;22,5409822');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '9', '53,4231311;14,5543913');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '9', '50,0648943;19,9247568');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '9', '52,4266545;16,9045472');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '9', '51,0910629;17,0247463');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '9', '50,0685377;19,953774');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '9', '52,2532834;20,8997839');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '9', '50,0568183;19,9374043');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '9', '53,424659;14,5355179');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '9', '50,0720444;19,9427961');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '9', '52,2952301;20,9599787');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '9', '50,2588539;19,0449471');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '9', '52,2237244;20,9941623');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '9', '50,6733476;17,9313677');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '9', '50,8227008;19,1157085');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '9', '50,0737515;19,9084188');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('47', '9', '53,1279072;23,158873');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '9', '53,4365409;14,5447293');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '9', '50,6830419;17,944603');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '9', '53,1167016;23,1461221');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '9', '50,0194251;21,9892104');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '9', '51,2355721;22,5502896');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '9', '50,8787077;20,6399417');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '9', '50,0292715;22,0155187');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '9', '52,2487966;21,0668711');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '9', '52,2684745;21,1773959');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '9', '50,8542686;20,6303877');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '9', '51,9364527;15,5070967');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '9', '53,1238436;17,9891123');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '9', '52,231828;21,005965');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '9', '53,1308472;18,0200985');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '9', '51,1179435;17,0906506');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '9', '51,7636738;19,4666458');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '9', '54,2036014;16,1971806');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '9', '52,6991772;21,0860544');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '9', '50,0721716;19,9993318');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '9', '52,217174;20,970847');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '9', '49,783632;19,0588884');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '9', '52,2296756;21,0122287');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '9', '52,3876684;16,9933168');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '9', '51,4075451;21,150924');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '9', '52,1716249;22,2833704');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '9', '52,1776819;21,015687');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '9', '52,3065935;20,984017');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '9', '50,8102099;19,1162359');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '9', '51,1078852;17,0385376');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '9', '52,2440137;20,9826743');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '9', '54,4525383;17,0419351');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '9', '50,212574;18,9769099');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '9', '50,050386;19,964959');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '9', '54,526523;18,511276');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '9', '50,0646501;19,9449799');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '9', '53,4291188;14,5641011');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '9', '51,775296;19,465142');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '9', '54,5438708;18,5450238');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '9', '54,3520252;18,6466384');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '9', '51,7462319;19,4690463');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '9', '50,2440933;18,9936852');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('1', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('2', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('3', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('4', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('5', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('6', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('7', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('8', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('9', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('10', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('11', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('12', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('13', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('14', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('15', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('16', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('17', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('18', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('19', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('20', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('21', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('22', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('23', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('24', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('25', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('26', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('27', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('28', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('29', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('30', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('31', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('32', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('33', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('34', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('35', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('36', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('37', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('38', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('39', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('40', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('41', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('42', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('43', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('44', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('45', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('46', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('47', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('48', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('49', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('50', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('51', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('52', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('53', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('54', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('55', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('56', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('57', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('58', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('59', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('60', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('61', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('62', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('63', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('64', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('65', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('66', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('67', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('68', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('69', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('70', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('71', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('72', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('73', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('74', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('75', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('76', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('77', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('78', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('79', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('80', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('81', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('82', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('83', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('84', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('85', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('86', '10', '0,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('87', '10', '1,0');
INSERT INTO CryteriaValues (universityID, cryteriaID, cryteriaValue) VALUES('88', '10', '1,0');